# Generated by Django 3.0.5 on 2022-12-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20221212_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='TUsers',
        ),
    ]
