# Generated by Django 3.0.5 on 2022-12-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20221213_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.CharField(max_length=30)),
                ('Total', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='TUsers',
        ),
    ]
