# Generated by Django 3.0.5 on 2022-12-14 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20221214_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
