# Generated by Django 3.0.5 on 2023-01-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_facility_questionnaire_questionnaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='active_till',
            new_name='expiry_date',
        ),
    ]
