# Generated by Django 3.0.5 on 2023-01-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20230112_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='expiry_date',
            new_name='active_till',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Facility_Questionnaire',
        ),
    ]
