# Generated by Django 3.0.5 on 2023-01-13 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20230113_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='active_till',
            field=models.DateField(verbose_name=datetime.datetime.now),
        ),
    ]
