# Generated by Django 3.0.5 on 2023-01-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20230115_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='isActive',
        ),
    ]
