# Generated by Django 3.0.5 on 2023-01-18 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20230117_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=750)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_questions', models.BigIntegerField(default=4)),
                ('active_till', models.DateField(verbose_name=datetime.datetime.now)),
                ('target_app', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TestQuestionnaires',
            },
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
