# Generated by Django 3.0.5 on 2023-01-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestionnaire',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
