# Generated by Django 3.0.5 on 2023-01-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20230119_1138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionnaireapi',
            table='QuestionnaireApis',
        ),
    ]
