# Generated by Django 4.2.1 on 2023-05-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20230119_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_male', models.BigIntegerField(default=4)),
                ('number_of_female', models.BigIntegerField(default=4)),
                ('number_of_reports', models.BigIntegerField(default=4)),
                ('target_app', models.CharField(max_length=45)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Total-reports-submitted',
                'ordering': ['-updated'],
            },
        ),
    ]
