# Generated by Django 4.2.1 on 2023-05-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_report'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='Final',
        ),
    ]
